### ISSUE TITLE
Error executing  `client.get_executed_orders(market="XLMCLP")`

### ISSUE THREAD

**Issue by fdelossantos** [cryptomkt/cryptomkt-python#15]
API and python library work well for other information, like get the balance or any other public or private endpoint. But when I try to get all executed orders for any market give me some error:

`message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.cryptomkt.com/v2/orders/executed?market=XLMCLP&limit=20&page=0')`

The response body is empty. It happen every time that I run this for any valid Market where I have orders.

My testing code:

```
from cryptomarket.exchange.client import Client
import os

CRYPTOMKT_API_KEY = os.getenv('CRYPTOMKT_API_KEY')
CRYPTOMKT_API_SECRET = os.getenv('CRYPTOMKT_API_SECRET')

client = Client(CRYPTOMKT_API_KEY, CRYPTOMKT_API_SECRET)
orders = client.get_executed_orders(market="XLMCLP")
print(orders)
```

Output:

```
Traceback (most recent call last):
  File "trades_history.py", line 9, in <module>
    orders = client.get_executed_orders(market="XLMCLP")
  File "/home/gustavo/dev/personal/turing/audit/venv/lib/python3.8/site-packages/cryptomarket/exchange/client.py", line 304, in get_executed_orders
    response = self._get(self.API_VERSION, 'orders', 'executed', params=params)
  File "/home/gustavo/dev/personal/turing/audit/venv/lib/python3.8/site-packages/cryptomarket/exchange/client.py", line 90, in _get
    return self._request('get', *args, **kwargs)
  File "/home/gustavo/dev/personal/turing/audit/venv/lib/python3.8/site-packages/cryptomarket/exchange/client.py", line 78, in _request
    return self._handle_response(response)
  File "/home/gustavo/dev/personal/turing/audit/venv/lib/python3.8/site-packages/cryptomarket/exchange/client.py", line 86, in _handle_response
    raise build_api_error(response)
  File "/home/gustavo/dev/personal/turing/audit/venv/lib/python3.8/site-packages/cryptomarket/exchange/error.py", line 78, in build_api_error
    blob = blob or response.json()
  File "/home/gustavo/dev/personal/turing/audit/venv/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by Insmael** [comment]
Hi,
the problem is for the deprecated sdk, in the current sdk your problem is no more.
