### ISSUE TITLE
El socket no se re-autoriza al reconectarse

### ISSUE THREAD

**Issue by miguelagustin** [cryptomkt/cryptomkt-python#6]
El socket imprime el siguiente mensaje:

"disconnected from server
connected to server"

Y deja de actualizar los mercados. Un workaround que encontré es reiniciandolo. Alguna idea de por qué sucede esto?

**Comment by miguelagustin** [comment]
Sigue sucediendo algo parecido, solo que esta vez cuando se desconecta entra en un bucle infinito, mostrando cada 1 segundo los siguientes mensajes:

disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server

**Comment by Insmael** [comment]
hola miguel, soy ismael y estoy trabajando en el issue.
he estado corriendo tests para replicar el error que pones pero no lo logro.
dejo corriendo los sockets un par de minutos y no se desconecta.
y cuando desconecto manualmente la conexión a internet y luego la vuelvo a conectar, el socket se reconecta bien nuevamente y sigue funcionando como debe.
se me ocurre que puede ser el problema de tu conexión a internet. En todo caso voy a seguir viendo como replicar tu problema, y si tienes más información de como estás usando el socket que puedas compartir nos ayudaría a encontrar el causante del problema

**Comment by miguelagustin** [comment]
Gracias por la ayuda Ismael. No se muy bien como reproducirlo tampoco. Pueden pasar horas hasta que empieza a hacer eso. Estoy siempre subscripto a ETHARS, ETHBRL, EOSARS, EOSBRL, XLMBRL y XLMARS. Dudo que sea el internet, ya que uso una instancia EC2 de AWS.

**Comment by Insmael** [comment]
ok miguel, voy a seguir viendo como podemos arreglar este issue, te mantengo al tanto

**Comment by Insmael** [comment]
miguel, logré replicar el error. como dijiste, corriendo el socket por algo mas de una hora con varias subscipciones hizo el truco.
vuelvo a cerrar el issue cuando tenga una solución al problema

**Comment by miguelagustin** [comment]
Recien me tiró lo siguiente:

disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server
disconnected from server
connected to server

y al segundo esta excepción en uno de mis threads:

`
Exception in thread Thread-498:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600                                                                 , in urlopen
    chunked=chunked)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384                                                                 , in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380                                                                 , in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line                                                                  302, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in                                                                  send
    timeout=timeout
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638                                                                 , in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in                                                                  increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685,                                                                  in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600                                                                 , in urlopen
    chunked=chunked)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384                                                                 , in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380                                                                 , in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line                                                                  302, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "cryptomkt_bot.py", line 575, in check_buy_orders
    if fiat.balance_changed():
  File "cryptomkt_bot.py", line 127, in balance_changed
    self._new_balance = self.get_balance()
  File "cryptomkt_bot.py", line 112, in get_balance
    balance =[x for x in cmkt.get_balance()['data'] if x['wallet'] == self.name.upper()][0]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cryptomarket/exchange/client.py", li                                                                 ne 433, in get_balance
    response = self._get(self.API_VERSION, 'balance')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cryptomarket/exchange/client.py", li                                                                 ne 90, in _get
    return self._request('get', *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cryptomarket/exchange/client.py", li                                                                 ne 77, in _request
    response = getattr(self.session, method)(uri, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 537, in                                                                  get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 524, in                                                                  request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 637, in                                                                  send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in                                                                  send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",)                                                                 )

`

Sin embargo despues de eso el socket siguió actualizando los mercados normalmente. Tal vez sirva para debuggear.
