### ISSUE TITLE
internal_error al usar transfer

### ISSUE THREAD

**Issue by dalacost** [cryptomkt/cryptomkt-python#9]
Obtengo este `internal_error` al solicitar una transferencia XLM , XXXX agregados intencionalmente. ¿Alguna idea que puede ser? 

```
Traceback (most recent call last):
  File "test.py", line XXXX, in <module>
    salida=cryptomkt_client.transfer(address="XXXX",amount=1.0,currency="xlm",memo="XXXX")
  File "XXXX/api_cryptomkt_python_test/cryptomkt-python-master/cryptomarket/exchange/client.py", line 520, in transfer
    response = self._post(self.API_VERSION, "transfer", data = params)
  File "XXXX/api_cryptomkt_python_test/cryptomkt-python-master/cryptomarket/exchange/client.py", line 93, in _post
    return self._request('post', *args, **kwargs)
  File "XXXX/api_cryptomkt_python_test/cryptomkt-python-master/cryptomarket/exchange/client.py", line 78, in _request
    return self._handle_response(response)
  File "XXXX/api_cryptomkt_python_test/cryptomkt-python-master/cryptomarket/exchange/client.py", line 86, in _handle_response
    raise build_api_error(response)
cryptomarket.exchange.error.InternalServerError: APIError(id=): internal_error
```

**Comment by dalacost** [comment]
parece q ya lo repararon. volví a ejecutar el codigo sin cambios y ahora va todo ok.
